#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# and "Hi" between the 9th and 10th iteration of "Best School"

i=0;
while ((i<10))
do
	if [ $i == 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++));
done
