#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# and "bad luck" at the 4th and 8th iteration

i=1;
while ((i<=20))
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	((i++))
done

# do
# 	echo "$i"
# 	if [ $i == 4 ]; then
# 		echo "bad luck from China"
# 	elif [ $i == 9 ]; then
# 		echo "bad luck from Japan"
# 	elif [ $i == 17 ]; then
# 		echo "bad luck from Italy"
# 	fi
# 	((i++));
# done
